# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\codes\project\gui\Recorder.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(806, 539)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(150, 50, 551, 401))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGetFile = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/104.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGetFile.setIcon(icon)
        self.btnGetFile.setObjectName("btnGetFile")
        self.horizontalLayout.addWidget(self.btnGetFile)
        self.editOutputFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.editOutputFile.setObjectName("editOutputFile")
        self.horizontalLayout.addWidget(self.editOutputFile)
        self.LabPassTime = QtWidgets.QLabel(self.groupBox_3)
        self.LabPassTime.setMinimumSize(QtCore.QSize(100, 0))
        self.LabPassTime.setObjectName("LabPassTime")
        self.horizontalLayout.addWidget(self.LabPassTime)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setContentsMargins(3, 2, 3, 2)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.spin_byteCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_byteCount.setMaximum(999999999)
        self.spin_byteCount.setObjectName("spin_byteCount")
        self.gridLayout_3.addWidget(self.spin_byteCount, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spin_duration = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_duration.setMaximum(999999999)
        self.spin_duration.setObjectName("spin_duration")
        self.gridLayout_3.addWidget(self.spin_duration, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spin_frameCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_frameCount.setMaximum(999999999)
        self.spin_frameCount.setObjectName("spin_frameCount")
        self.gridLayout_3.addWidget(self.spin_frameCount, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.spin_sampleCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_sampleCount.setMaximum(999999999)
        self.spin_sampleCount.setObjectName("spin_sampleCount")
        self.gridLayout_3.addWidget(self.spin_sampleCount, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.spin_channelCount = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_channelCount.setObjectName("spin_channelCount")
        self.gridLayout_4.addWidget(self.spin_channelCount, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.edit_byteOrder = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_byteOrder.setObjectName("edit_byteOrder")
        self.gridLayout_4.addWidget(self.edit_byteOrder, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.edit_codec = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_codec.setObjectName("edit_codec")
        self.gridLayout_4.addWidget(self.edit_codec, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.edit_sampleType = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_sampleType.setObjectName("edit_sampleType")
        self.gridLayout_4.addWidget(self.edit_sampleType, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 4, 0, 1, 1)
        self.spin_sampleSize = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_sampleSize.setMaximum(999)
        self.spin_sampleSize.setObjectName("spin_sampleSize")
        self.gridLayout_4.addWidget(self.spin_sampleSize, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 5, 0, 1, 1)
        self.spin_sampleRate = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_sampleRate.setMaximum(9999999)
        self.spin_sampleRate.setObjectName("spin_sampleRate")
        self.gridLayout_4.addWidget(self.spin_sampleRate, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 6, 0, 1, 1)
        self.spin_bytesPerFrame = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_bytesPerFrame.setMaximum(999999)
        self.spin_bytesPerFrame.setObjectName("spin_bytesPerFrame")
        self.gridLayout_4.addWidget(self.spin_bytesPerFrame, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.gridLayout_6.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboDevices = QtWidgets.QComboBox(self.groupBox)
        self.comboDevices.setObjectName("comboDevices")
        self.gridLayout.addWidget(self.comboDevices, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboCodec = QtWidgets.QComboBox(self.groupBox)
        self.comboCodec.setObjectName("comboCodec")
        self.gridLayout.addWidget(self.comboCodec, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboSampleRate = QtWidgets.QComboBox(self.groupBox)
        self.comboSampleRate.setObjectName("comboSampleRate")
        self.gridLayout.addWidget(self.comboSampleRate, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboChannels = QtWidgets.QComboBox(self.groupBox)
        self.comboChannels.setObjectName("comboChannels")
        self.gridLayout.addWidget(self.comboChannels, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBitrate = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBitrate.setObjectName("comboBitrate")
        self.gridLayout_5.addWidget(self.comboBitrate, 1, 1, 1, 1)
        self.radioQuality = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioQuality.setChecked(True)
        self.radioQuality.setObjectName("radioQuality")
        self.gridLayout_5.addWidget(self.radioQuality, 0, 0, 1, 1)
        self.sliderQuality = QtWidgets.QSlider(self.groupBox_2)
        self.sliderQuality.setMaximum(8)
        self.sliderQuality.setOrientation(QtCore.Qt.Horizontal)
        self.sliderQuality.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderQuality.setTickInterval(1)
        self.sliderQuality.setObjectName("sliderQuality")
        self.gridLayout_5.addWidget(self.sliderQuality, 0, 1, 1, 1)
        self.radioBitrate = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBitrate.setChecked(False)
        self.radioBitrate.setObjectName("radioBitrate")
        self.gridLayout_5.addWidget(self.radioBitrate, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.actRecordStart = QtWidgets.QAction(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/626.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecordStart.setIcon(icon1)
        self.actRecordStart.setObjectName("actRecordStart")
        self.actRecordPause = QtWidgets.QAction(Form)
        self.actRecordPause.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecordPause.setIcon(icon2)
        self.actRecordPause.setObjectName("actRecordPause")
        self.actRecordStop = QtWidgets.QAction(Form)
        self.actRecordStop.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecordStop.setIcon(icon3)
        self.actRecordStop.setObjectName("actRecordStop")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnGetFile.setText(_translate("Form", "录音输出文件"))
        self.LabPassTime.setText(_translate("Form", "已录时间："))
        self.groupBox_4.setTitle(_translate("Form", "探测QAudioBuffer信息"))
        self.label_6.setText(_translate("Form", "缓冲区字节数"))
        self.spin_byteCount.setSuffix(_translate("Form", "  bytes"))
        self.label_7.setText(_translate("Form", "缓冲区时长(ms)"))
        self.spin_duration.setSuffix(_translate("Form", "  ms"))
        self.label_8.setText(_translate("Form", "缓冲区帧数"))
        self.label_9.setText(_translate("Form", "采样数"))
        self.groupBox_5.setTitle(_translate("Form", "QAudioFormat信息"))
        self.label_10.setText(_translate("Form", "channelCount"))
        self.label_11.setText(_translate("Form", "byteOrder"))
        self.label_12.setText(_translate("Form", "codec"))
        self.label_13.setText(_translate("Form", "sampleType"))
        self.label_14.setText(_translate("Form", "sampleSize"))
        self.spin_sampleSize.setSuffix(_translate("Form", "  bits"))
        self.label_15.setText(_translate("Form", "sampleRate"))
        self.spin_sampleRate.setSuffix(_translate("Form", "  Hz"))
        self.label_16.setText(_translate("Form", "bytesPerFrame"))
        self.spin_bytesPerFrame.setSuffix(_translate("Form", "  bytes"))
        self.groupBox.setTitle(_translate("Form", "录音设置（QAudioEncoderSettings）"))
        self.label.setText(_translate("Form", "输入设备"))
        self.label_2.setText(_translate("Form", "音频编码"))
        self.label_3.setText(_translate("Form", "采样率"))
        self.label_4.setText(_translate("Form", "通道数"))
        self.groupBox_2.setTitle(_translate("Form", "编码模式"))
        self.radioQuality.setText(_translate("Form", "固定品质"))
        self.radioBitrate.setText(_translate("Form", "固定比特率"))
        self.actRecordStart.setText(_translate("Form", "录音"))
        self.actRecordStart.setToolTip(_translate("Form", "录音"))
        self.actRecordPause.setText(_translate("Form", "暂停"))
        self.actRecordPause.setToolTip(_translate("Form", "暂停"))
        self.actRecordStop.setText(_translate("Form", "停止"))
        self.actRecordStop.setToolTip(_translate("Form", "停止"))
